import { UserAvatar } from '../../../../../src/contexts/iam/users/domain/value-objects/UserAvatar';

describe('UserAvatar', () => {
  describe('fromName', () => {
    it('genera una URL de ui-avatars con el nombre codificado', () => {
      const avatar = UserAvatar.fromName('Ada', 'Lovelace');
      expect(avatar.value).toContain('https://ui-avatars.com/api/');
      expect(avatar.value).toContain('Ada%20Lovelace');
      expect(avatar.value).toContain('background=random');
    });
  });

  describe('isAutoGenerated', () => {
    it('reconoce como autogenerado un avatar creado con fromName', () => {
      expect(UserAvatar.fromName('Ada', 'Lovelace').isAutoGenerated()).toBe(
        true,
      );
    });

    it('no considera autogenerado un avatar real (foto subida)', () => {
      expect(
        new UserAvatar(
          'https://cdn.test/avatars/foto-real.webp',
        ).isAutoGenerated(),
      ).toBe(false);
    });
  });
});
