import { StringValueObject } from '../../../../../common/domain';

export class UserAvatar extends StringValueObject {
  private static readonly DEFAULT_AVATAR_BASE = 'https://ui-avatars.com/api/';

  static fromName(firstName: string, lastName: string): UserAvatar {
    const name = encodeURIComponent(`${firstName} ${lastName}`);
    return new UserAvatar(
      `${UserAvatar.DEFAULT_AVATAR_BASE}?name=${name}&background=random`,
    );
  }

  /**
   * Distingue el avatar default (generado a partir del nombre) de uno
   * "real" — sea una foto de Google o una imagen que el usuario subió.
   * Lo usamos para decidir si una operación que regenera el default
   * (ej. cambiar el nombre) debe pisar el avatar actual o respetarlo.
   */
  isAutoGenerated(): boolean {
    return this.value.startsWith(UserAvatar.DEFAULT_AVATAR_BASE);
  }
}
