import { Inject, Injectable } from '@nestjs/common';
import { CLOCK, Clock } from '../../../../../common/domain';
import { User } from '../../domain/User';
import { UserAvatar } from '../../domain/value-objects/UserAvatar';
import { UserEmail } from '../../domain/value-objects/UserEmail';
import { UserFirstName } from '../../domain/value-objects/UserFirstName';
import { UserId } from '../../domain/value-objects/UserId';
import { UserLastName } from '../../domain/value-objects/UserLastName';
import { USER_REPOSITORY, UserRepository } from '../../domain/UserRepository';
import { GoogleAuthUserCommand } from './GoogleAuthUserCommand';

@Injectable()
export class GoogleAuthUserHandler {
  constructor(
    @Inject(USER_REPOSITORY)
    private readonly userRepository: UserRepository,
    @Inject(CLOCK)
    private readonly clock: Clock,
  ) {}

  async execute(command: GoogleAuthUserCommand): Promise<User> {
    const email = new UserEmail(command.email);

    const existingUser = await this.userRepository.findByEmail(email);

    if (existingUser) {
      // Si el usuario ya existe pero todavía tiene el avatar default
      // generado a partir del nombre, lo reemplazamos con la foto del
      // proveedor OAuth. Si ya tiene una foto real, no la pisamos.
      if (command.avatar) {
        const primitives = existingUser.toPrimitives();
        const currentAvatar = primitives.avatar
          ? new UserAvatar(primitives.avatar)
          : null;
        if (!currentAvatar || currentAvatar.isAutoGenerated()) {
          existingUser.changeAvatar(new UserAvatar(command.avatar), this.clock);
          await this.userRepository.save(existingUser);
        }
      }
      return existingUser;
    }

    const user = User.create(
      {
        id: new UserId(command.id),
        firstName: new UserFirstName(command.firstName),
        lastName: new UserLastName(command.lastName),
        email,
        emailVerified: true,
        avatar: command.avatar ? new UserAvatar(command.avatar) : null,
      },
      this.clock,
    );

    await this.userRepository.save(user);

    return user;
  }
}
